# Generated by Django 5.2.4 on 2025-08-11 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. cost of living, local shops, ...', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='e.g. cost_of_living, local_shops, ...', unique=True)),
                ('left_label', models.CharField(help_text="Not good. e.g. 'Expensive', 'Low', ...", max_length=100)),
                ('right_label', models.CharField(help_text="Good. e.g. 'Cheap', 'High', ...", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.prefecture')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamu.country')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamu.municipality')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.criteria')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.municipality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityBaseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_score', models.FloatField(default=0.0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.country')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.criteria')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.municipality')),
            ],
            options={
                'unique_together': {('municipality', 'criteria')},
            },
        ),
        migrations.CreateModel(
            name='MunicipalityMatchingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.country')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.criteria')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.municipality')),
            ],
            options={
                'unique_together': {('municipality', 'country', 'criteria')},
            },
        ),
    ]
