# Generated by Django 5.2.4 on 2025-08-08 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_cost_of_living', models.FloatField(default=0.0)),
                ('base_local_shops', models.FloatField(default=0.0)),
                ('base_temperature', models.FloatField(default=0.0)),
                ('base_crime_rate', models.FloatField(default=0.0)),
                ('base_population', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_number', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.city')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamu.city')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamu.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_of_living_score', models.IntegerField(default=0)),
                ('local_shops_score', models.IntegerField(default=0)),
                ('temperature_score', models.IntegerField(default=0)),
                ('crime_rate_score', models.IntegerField(default=0)),
                ('population_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_cost_of_living', models.FloatField(default=0.0)),
                ('avg_local_shops', models.FloatField(default=0.0)),
                ('avg_temperature', models.FloatField(default=0.0)),
                ('avg_crime_rate', models.FloatField(default=0.0)),
                ('avg_population', models.FloatField(default=0.0)),
                ('final_cost_of_living', models.FloatField(default=0.0)),
                ('final_local_shops', models.FloatField(default=0.0)),
                ('final_temperature', models.FloatField(default=0.0)),
                ('final_crime_rate', models.FloatField(default=0.0)),
                ('final_population', models.FloatField(default=0.0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.city')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.nationality')),
            ],
            options={
                'unique_together': {('city', 'nationality')},
            },
        ),
    ]
