# Generated by Django 5.2.4 on 2025-08-08 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. cost of living, local shops, ...', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='e.g. cost_of_living, local_shops, ...', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.city')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamu.nationality')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamu.province')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.criteria')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceBaseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_score', models.FloatField(default=0.0)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.criteria')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.province')),
            ],
            options={
                'unique_together': {('province', 'criteria')},
            },
        ),
        migrations.CreateModel(
            name='ProvinceMatchingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.criteria')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.nationality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.province')),
            ],
            options={
                'unique_together': {('province', 'nationality', 'criteria')},
            },
        ),
    ]
