# Generated by Django 5.2.4 on 2025-08-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='left_label',
            field=models.CharField(help_text="Not good. e.g. 'Expensive', 'Low', ...", max_length=100),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='right_label',
            field=models.CharField(help_text="Good. e.g. 'Cheap', 'High', ...", max_length=100),
        ),
    ]
