# Generated by Django 5.2.4 on 2025-08-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamu', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipalitybasescore',
            unique_together={('municipality', 'country', 'criteria')},
        ),
    ]
