# Generated by Django 5.2.4 on 2025-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamu', '0002_alter_municipalitybasescore_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='is_reverse',
            field=models.BooleanField(default=False),
        ),
    ]
