# Generated by Django 5.2.4 on 2025-08-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamu', '0002_alter_user_birthday_alter_user_current_residence_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
    ]
