# Generated by Django 5.2.4 on 2025-08-12 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamu', '0003_criteria_is_reverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='target_prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamu.prefecture'),
        ),
    ]
