# Generated by Django 5.2.4 on 2025-08-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamu', '0003_rename_user_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationsurvey',
            old_name='user',
            new_name='user_info',
        ),
    ]
