# Generated by Django 5.2.4 on 2025-08-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamu', '0004_userinfo_target_prefecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
