# Generated by Django 5.2.4 on 2025-08-14 02:25

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamu', '0005_municipality_latitude_municipality_longitude'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipalitymatchingscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='municipalitymatchingscore',
            name='country',
        ),
        migrations.RemoveField(
            model_name='municipalitymatchingscore',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='municipalitymatchingscore',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='target_prefecture',
        ),
        migrations.AlterField(
            model_name='criteria',
            name='left_label',
            field=models.CharField(help_text="Good. e.g. 'Cheap', 'Safe', ...", max_length=100),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(help_text="Name of the criteria, e.g. 'Cost of Living', 'Safety', etc.", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='right_label',
            field=models.CharField(help_text="Bad. e.g. 'Expensive', 'Unsafe', ...", max_length=100),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.CreateModel(
            name='MunicipalityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_score', models.FloatField(default=0.0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.country')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.criteria')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamu.municipality')),
            ],
            options={
                'unique_together': {('municipality', 'country', 'criteria')},
            },
        ),
        migrations.DeleteModel(
            name='MunicipalityBaseScore',
        ),
        migrations.DeleteModel(
            name='MunicipalityMatchingScore',
        ),
    ]
