# Generated by Django 5.2.4 on 2025-08-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamu', '0006_alter_municipalitymatchingscore_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='left_label',
            field=models.CharField(help_text='Low index', max_length=100),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='right_label',
            field=models.CharField(help_text='High index', max_length=100),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='slug',
            field=models.SlugField(help_text='A short label for URL, must be unique.', max_length=100, unique=True),
        ),
    ]
